% run_matlab_collisions.m
% --------------------------------------------------------------------------
% MATLAB equivalent of run_python_collisions.py.
%
% Loads the same init_state.csv generated by generate_init_state.py and
% runs a 200-step collision-only simulation using the same physics as the
% legacy Mode-3 code. No Morse, no droplet force -- atoms free-stream
% between collisions.
%
% Outputs:
%   matlab_summary.csv -- one row per timestep
%   matlab_collision_events.csv -- one row per collision event
%
% Run with:
%   matlab -batch "run_matlab_collisions"
%
% Adjust MATLAB_LEGACY_DIR below to point to your copy of the legacy
% Iodine_Helium_Simulation/ directory.
% --------------------------------------------------------------------------

clear; close all;

% --- paths and seed ---
MATLAB_LEGACY_DIR = '../../../Iodine_Helium_Simulation';
addpath(fullfile(MATLAB_LEGACY_DIR, 'additional_functions'));
rng(12345);   % match RNG_SEED in run_python_collisions.py (sequences will
              % differ but distributions should agree)

% --- parameters (match run_python_collisions.py) ---
NUM_STEPS = 200;
DT_PS = 0.01;
DROPLET_RADIUS_A = 27.97;

% --- physical constants (legacy MATLAB values) ---
u = 1.66053907e-27;
eV = 1.602e-19;
mass_amu = 127.0;

% --- collision parameters ---
sigma = 30.0;                            % geometric cross section [A^2]
density_droplet = 0.8 * 0.0219;          % atoms/A^3
scatter_mass_neutral = 4.0;              % He, in amu
neutral_scatter_angle_std_deg = 0;
E_min_eV = 0.05;                          % matches Python cfg.E_min_eV at default

% --- read init state ---
init = readmatrix('init_state.csv', 'NumHeaderLines', 1);
n_atoms = size(init, 1);
x = init(:, 2);   y = init(:, 3);   z = init(:, 4);
vx = init(:, 5);  vy = init(:, 6);  vz = init(:, 7);

m = mass_amu * u * ones(n_atoms, 1);    % per-atom mass (kg)
RHO_mass = (m / u) / scatter_mass_neutral;

fprintf('Loaded %d atoms.\n', n_atoms);

% --- bookkeeping ---
E_dissip_cum = zeros(n_atoms, 1);
n_coll_cum   = zeros(n_atoms, 1);

% --- output buffers ---
summary_out = zeros(NUM_STEPS + 1, 7);
event_buf = cell(NUM_STEPS, 1);   % per-step event lists, concat at end

% Helpers
compute_E_kin = @(vx, vy, vz) 0.5 * m .* ((vx.^2 + vy.^2 + vz.^2) * 100^2) / eV;

% Record t=0
E_kin = compute_E_kin(vx, vy, vz);
summary_out(1, :) = [0.0, mean(E_kin), var(E_kin, 1), ...
                     mean(E_dissip_cum), var(E_dissip_cum, 1), ...
                     0, 0];

% Main loop
prev_distance = [];
for step_idx = 1:NUM_STEPS
    t_ps = step_idx * DT_PS;

    % 1. Free-stream
    x_new = x + vx * DT_PS;
    y_new = y + vy * DT_PS;
    z_new = z + vz * DT_PS;

    % 2. Depth
    r_new = sqrt(x_new.^2 + y_new.^2 + z_new.^2);
    depth = r_new - DROPLET_RADIUS_A;

    % 3. Pre-collision energy (computed from CURRENT velocity, which hasn't
    %    been changed yet). E0 has shape (n_atoms,1).
    E0 = compute_E_kin(vx, vy, vz);

    % 4. Sample collisions (Mode 3) -- uses the *previous* step's distance
    if isempty(prev_distance)
        b_collision = false(n_atoms, 1);
    else
        trial_random_number = rand(n_atoms, 1);
        p_scatter = prev_distance .* sigma * density_droplet;
        b_collision = (trial_random_number < p_scatter) & (depth < 0);
        % Landau cutoff
        b_landau = E0 < E_min_eV;
        b_collision = b_collision & ~b_landau;
    end

    % --- 5. Apply collisions (mirroring vmi_sim_3d_neutral_propa_HeDFT_mimic.m) ---
    % NOTE: legacy MATLAB draws random numbers *for all atoms* every step,
    % regardless of whether they collide. We mirror that to keep the RNG
    % stream identical to the production code. (The samples for non-colliders
    % are simply discarded later.)

    impact_parameter_norm = sqrt(rand(n_atoms, 1));    % b/R
    COSTHETA = 2 * impact_parameter_norm.^2 - 1;
    SINTHETA = sqrt(1 - COSTHETA.^2);

    COSTHETA(~b_collision) = 1;
    SINTHETA(~b_collision) = 0;

    E1 = E0 .* (1 + 2 * RHO_mass .* COSTHETA + RHO_mass.^2) ./ (1 + RHO_mass).^2;

    % CM -> lab transform
    COStheta = (COSTHETA + RHO_mass) ./ sqrt(1 + 2 * RHO_mass .* COSTHETA + RHO_mass.^2);
    SINtheta = sqrt(1 - COStheta.^2);

    % Optional Gaussian smearing (zero by default)
    if neutral_scatter_angle_std_deg > 0
        theta = acos(COStheta(b_collision)) + ...
                randn(sum(b_collision), 1) * neutral_scatter_angle_std_deg * pi / 180;
        COStheta(b_collision) = cos(theta);
        SINtheta(b_collision) = sqrt(1 - COStheta(b_collision).^2);
    end

    % Build orthonormal basis perpendicular to v
    v_speed = sqrt(vx.^2 + vy.^2 + vz.^2);
    v_unit_x = vx ./ v_speed;
    v_unit_y = vy ./ v_speed;
    v_unit_z = vz ./ v_speed;
    velocity_unit_vectors = [v_unit_x, v_unit_y, v_unit_z];

    reference_direction = rand(n_atoms, 3) - 0.5;
    reference_direction = reference_direction ./ ...
                          sqrt(sum(reference_direction.^2, 2));

    velocity_normal_1 = cross(velocity_unit_vectors, reference_direction, 2);
    velocity_normal_1 = velocity_normal_1 ./ ...
                        sqrt(sum(velocity_normal_1.^2, 2));
    velocity_normal_2 = cross(velocity_unit_vectors, velocity_normal_1, 2);

    COSBETA = (rand(n_atoms, 1) - 0.5) * 2;
    SINBETA = sqrt(1 - COSBETA.^2);

    v_new_speed = sqrt(2 * E1 * eV ./ m) / 100;
    v_normal = v_new_speed .* SINtheta;
    v_parallel = v_new_speed .* COStheta;

    new_velocity_vectors = velocity_unit_vectors .* v_parallel ...
        + velocity_normal_1 .* COSBETA .* v_normal ...
        + velocity_normal_2 .* SINBETA .* v_normal;

    vx_after = new_velocity_vectors(:, 1);
    vy_after = new_velocity_vectors(:, 2);
    vz_after = new_velocity_vectors(:, 3);

    % For non-colliders, keep original velocity (the formula above might
    % introduce tiny numerical errors due to the orthonormalization; we
    % explicitly preserve incoming velocity for non-colliders to match
    % the Python apply_collision contract).
    vx_after(~b_collision) = vx(~b_collision);
    vy_after(~b_collision) = vy(~b_collision);
    vz_after(~b_collision) = vz(~b_collision);

    % Energy loss per atom (zero for non-colliders since E0 = E1 there)
    actual_dE = zeros(n_atoms, 1);
    actual_dE(b_collision) = E0(b_collision) - E1(b_collision);

    % 6. Bookkeeping
    E_dissip_cum = E_dissip_cum + actual_dE;
    n_coll_cum   = n_coll_cum + b_collision;

    % Log per-event
    coll_indices = find(b_collision);
    if ~isempty(coll_indices)
        events = [repmat(t_ps, length(coll_indices), 1), ...
                  coll_indices - 1, ...   % 0-based to match Python
                  actual_dE(coll_indices), ...
                  E0(coll_indices)];
        event_buf{step_idx} = events;
    end

    % 7. Distance for next step
    prev_distance = sqrt((x_new - x).^2 + (y_new - y).^2 + (z_new - z).^2);

    % 8. Advance
    x = x_new; y = y_new; z = z_new;
    vx = vx_after; vy = vy_after; vz = vz_after;

    % Record summary
    E_kin = compute_E_kin(vx, vy, vz);
    summary_out(step_idx + 1, :) = [t_ps, mean(E_kin), var(E_kin, 1), ...
                                     mean(E_dissip_cum), var(E_dissip_cum, 1), ...
                                     sum(b_collision), sum(n_coll_cum)];
end

% --- write CSVs ---
% Summary
fid = fopen('matlab_summary.csv', 'w');
fprintf(fid, 't_ps,mean_E_kin_eV,var_E_kin_eV,mean_E_dissip_eV,var_E_dissip_eV,n_coll_this_step,n_coll_cumulative\n');
for ii = 1:size(summary_out, 1)
    fprintf(fid, '%.16e,%.16e,%.16e,%.16e,%.16e,%d,%d\n', ...
        summary_out(ii, 1), summary_out(ii, 2), summary_out(ii, 3), ...
        summary_out(ii, 4), summary_out(ii, 5), ...
        round(summary_out(ii, 6)), round(summary_out(ii, 7)));
end
fclose(fid);

% Events (concatenate all per-step lists)
all_events = vertcat(event_buf{:});
fid = fopen('matlab_collision_events.csv', 'w');
fprintf(fid, 't_ps,atom_idx,dE_eV,E0_eV\n');
if ~isempty(all_events)
    for ii = 1:size(all_events, 1)
        fprintf(fid, '%.16e,%d,%.16e,%.16e\n', ...
            all_events(ii, 1), round(all_events(ii, 2)), ...
            all_events(ii, 3), all_events(ii, 4));
    end
end
fclose(fid);

% --- summary ---
fprintf('\nWrote matlab_summary.csv (%d rows)\n', size(summary_out, 1));
fprintf('Wrote matlab_collision_events.csv (%d events)\n', size(all_events, 1));
fprintf('\nFinal state:\n');
fprintf('  Total collisions: %d\n', size(all_events, 1));
fprintf('  Avg collisions per atom: %.2f\n', size(all_events, 1) / n_atoms);
fprintf('  Mean E_kin at end: %.6f eV (started at %.6f)\n', ...
        summary_out(end, 2), summary_out(1, 2));
fprintf('  Mean E_dissip at end: %.6f eV\n', summary_out(end, 4));
fprintf('  Energy balance: start mean E_kin - end = %.6f vs E_dissip = %.6f\n', ...
        summary_out(1, 2) - summary_out(end, 2), summary_out(end, 4));
